Implemented PKCE Authorization Flow
supabase-community/gotrue-swift pull request #65
Opened 2023-07-31 12:50 UTC by ljubiknenad

## What kind of change does this PR introduce?

This PR consist implementation of PKCE Authorization Flow for `getOAuthSignInURL` & `signInWithOTP` methods.

## What is the current behavior?

## What is the new behavior?

When initializing a client there is a new property called `flowType` which is of type FlowType enum that consist of two types:

- implicit
- pkce

example:
`let client = GoTrueClient(url: "", headers: [:], flowType: .pkce)`

The flowType property has default value of `.implicit`

## Additional context

2023-07-31 17:01 UTC, grsouza requested changes

2023-07-31 17:01 UTC, grdsdev commented on Sources/GoTrue/GoTrueClient.swift
> +  public let flowType: FlowType!
No need to be a unwrapped optional.

```suggestion
  public let flowType: FlowType
```

2023-07-31 17:01 UTC, grdsdev commented on Sources/GoTrue/Types.swift
> +        return Data(buffer).base64EncodedString()
Just confirming, should we use `pkceBase64EncodedString` here too?

2023-07-31 17:01 UTC, grdsdev commented on Sources/GoTrue/Endpoints.swift
> +      }
I don't think we need another `post` method, just adding pkce options to `GrantType` and `PostRequest` should be enough, and then the GoTrueClient should reuse the already existing `post` method.

2023-07-31 17:01 UTC, grdsdev commented on Sources/GoTrue/GoTrueClient.swift
> +    public func session(from url: URL, storeSession: Bool = true) async throws -> Session {
Add docs and `discardableResult` to this method too, remove from the private one.

2023-07-31 17:01 UTC, grdsdev commented on Sources/GoTrue/GoTrueError.swift
> +  case codeNotFound
```suggestion
  case pkceCodeNotFound
```

2023-07-31 17:01 UTC, grdsdev commented on Sources/GoTrue/GoTrueError.swift
> +    case .codeNotFound: return "Unable to get a valid code."
```suggestion
    case .pkceCodeNotFound: return "A valid PKCE code was not found."
```

2023-07-31 17:01 UTC, grsouza commented on Sources/GoTrue/Types.swift
> +  public var codeChallengeMethod: String?
Would be nice to have a `enum` representing the codeChallgendMethod, even we if we have single method.

```swift
public enum PKCECodeChallengeMethod: String {
    case sha256 = "S256"
}
```

2023-08-01 13:17 UTC, ljubiknenad commented on Sources/GoTrue/Types.swift
> +        return Data(buffer).base64EncodedString()
Yup. As i saw the same is on Android

2023-08-01 14:05 UTC, grsouza requested changes

2023-08-01 14:05 UTC, grdsdev commented on Sources/GoTrue/Endpoints.swift
> +    }
Remove as it isn't being used

2023-08-04 12:18 UTC, grsouza requested changes

2023-08-04 12:18 UTC, grsouza commented on Sources/GoTrue/Types.swift
> +public struct PKCEParams: Codable, Hashable, Sendable {
I'd rename this for consistency.

```suggestion
public struct PKCECredentials Codable, Hashable, Sendable {
```

2023-08-04 12:19 UTC, grsouza commented on Sources/GoTrue/Types.swift
> +        return Data(buffer).base64EncodedString()
Didn't get it, should we use `pkceBase64EncodedString`?

2023-08-08 07:56 UTC, ljubiknenad commented on Sources/GoTrue/Types.swift
> +        return Data(buffer).base64EncodedString()
Yes, we should use `pkceBase64EncodedString`

2023-08-08 08:11 UTC, grsouza requested changes

2023-08-08 08:11 UTC, grsouza commented on Sources/GoTrue/Types.swift
> +        return Data(buffer).base64EncodedString()
```suggestion
        return Data(buffer).pkceBase64EncodedString()
```

2023-08-08 13:28 UTC, grsouza approved these changes

2023-10-30 13:48 UTC, grdsdev commented
Closing in favor of: https://github.com/supabase-community/supabase-swift/pull/119

2023-10-30 13:48 UTC, closed without merging